2022-04-08 16:34:59,714 - ERROR - test02_Home.py[:93] - 测试未通过 '' != '菜单名称'
+ 菜单名称
Traceback (most recent call last):
  File "E:\Study\pythonProject\pythonProject\my_selenium_project\testcases\test02_Home.py", line 90, in test03_enter_menu_manage
    self.assertEqual(result.text, '菜单名称')
  File "C:\Program Files\Python38\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Program Files\Python38\lib\unittest\case.py", line 1292, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Program Files\Python38\lib\unittest\case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: '' != '菜单名称'
+ 菜单名称
